rd /S /Q ".\AvalonDock\obj"
rd /S /Q ".\AvalonDock\bin"
rd /S /Q ".\AvalonDock.DemoApp\obj"
rd /S /Q ".\AvalonDock.DemoApp\bin"
rd /S /Q ".\AvalonDock.Themes\obj"
rd /S /Q ".\AvalonDock.Themes\bin"
rd /S /Q ".\Sample1\obj"
rd /S /Q ".\Sample1\bin"
rd /S /Q ".\Sample2\obj"
rd /S /Q ".\Sample2\bin"
rd /S /Q ".\Sample3\obj"
rd /S /Q ".\Sample3\bin"
rd /S /Q ".\Sample4\obj"
rd /S /Q ".\Sample4\bin"

